// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define CppCodegenTest_Class4_BODY

/************************************************************
 Class4 class body
 ************************************************************/

// include associated header file
#include "CppCodegenTest/Class4.h"

// Derived includes directives

// static attributes (if any)
/**
 * 
 */
char* Class4::charStringStaticInit = "Hello World";

/************************************************************
 End of Class4 class body
 ************************************************************/