// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define CppCodegenTest_Class6_BODY

/************************************************************
 Class6 class body
 ************************************************************/

// include associated header file
#include "CppCodegenTest/Class6.h"

// Derived includes directives

// static attributes (if any)

/************************************************************
 End of Class6 class body
 ************************************************************/