// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define CppCodegenTest_Class7_BODY

/************************************************************
 Class7 class body
 ************************************************************/

// include associated header file
#include "CppCodegenTest/Class7.h"

// Derived includes directives

// static attributes (if any)
/**
 * 
 */
int Class7::staticProp;

/************************************************************
 End of Class7 class body
 ************************************************************/