// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef CPPCODEGENTEST_CLASS5_H
#define CPPCODEGENTEST_CLASS5_H

/************************************************************
 Class5 class header
 ************************************************************/

#include "CppCodegenTest/Pkg_CppCodegenTest.h"

#include "AnsiCLibrary/Pkg_AnsiCLibrary.h"

/************************************************************/
/**
 * C++ Virtual Interface
 */

class Class5 {

public:

	/**
	 * 
	 */
	int externalProp;

	/**
	 * 
	 * @param iReturn 
	 */
	virtual int pureVirtualOp() = 0;

	/**
	 * 
	 * @param iReturn 
	 */
	virtual int* pureVirtualConstOp() = 0;

};
/************************************************************/
/* External declarations (package visibility)               */

/************************************************************/

/* Inline functions                                         */

/************************************************************
 End of Class5 class header
 ************************************************************/

#endif
