// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define CppCodegenTest_Class5_BODY

/************************************************************
 Class5 class body
 ************************************************************/

// include associated header file
#include "CppCodegenTest/Class5.h"

// Derived includes directives

// static attributes (if any)

/************************************************************
 End of Class5 class body
 ************************************************************/