// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef CPPCODEGENTEST_CLASS1_H
#define CPPCODEGENTEST_CLASS1_H

/************************************************************
 Class1 class header
 ************************************************************/

#include "CppCodegenTest/Pkg_CppCodegenTest.h"

#include "AnsiCLibrary/Pkg_AnsiCLibrary.h"

/************************************************************/
/**
 * 
 */
class Class1 {
public:

	/**
	 * Assignment operator
	 * @param cSource 
	 * @return this 
	 */
	Class1& operator =(const Class1 /*in*/& cSource);

	/**
	 * Destructor
	 */
	~Class1();

	/**
	 * Copy constructor
	 * @param cSource 
	 */
	Class1(const Class1 /*in*/& cSource);

private:
	/**
	 * 
	 */
	int iVal;
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

/************************************************************
 End of Class1 class header
 ************************************************************/

#endif
