// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef CPPCODEGENTEST_PACKAGE1_CLASS9_H
#define CPPCODEGENTEST_PACKAGE1_CLASS9_H

/************************************************************
 Class9 class header
 ************************************************************/

#include "CppCodegenTest/Package1/Pkg_Package1.h"

#include "AnsiCLibrary/Pkg_AnsiCLibrary.h"

namespace Package1 {

/************************************************************/
/**
 * 
 */
class Class9 {
public:
	Class9() :
			externAttribute(3) {
	}
	/**
	 * 
	 */
	int volatileAttribute;
	/**
	 * Should not generate 'register' keyword as 'register' only applies to properties declared within the scope of an operation.
	 */
	int registerAttribute;

	/**
	 * 
	 * @return  
	 */
	int volatileIntOperation();

	/**
	 * Should not generate the 'register' keyword as it cannot be used in method signatures.
	 * @return  
	 */
	int registerOperation();

};
/************************************************************/
/* External declarations (package visibility)               */
/**
 * 
 */
int externAttribute;

/**
 * 
 * @return  
 */
int externOperation();
/************************************************************/

/* Inline functions                                         */

} // of namespace Package1

/************************************************************
 End of Class9 class header
 ************************************************************/

#endif
