// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef CPPCODEGENTEST_PACKAGE1_CLASS8_H
#define CPPCODEGENTEST_PACKAGE1_CLASS8_H

/************************************************************
 Class8 class header
 ************************************************************/

#include "CppCodegenTest/Package1/Pkg_Package1.h"

#include "AnsiCLibrary/Pkg_AnsiCLibrary.h"

namespace Package1 {

/************************************************************/
/**
 * 
 */
class Class8 {
public:
	Class8() :
			defaultIValue(12) {
	}
	/**
	 * 
	 */
	int defaultIValue;

	/**
	 * 
	 * @param iVal1 
	 * @param iVal2 
	 * @param cVal1 
	 * @param cVal2 
	 * @return this 
	 */
	int operation1(int /*in*/iVal1, int /*in*/iVal2 = 2, char /*in*/cVal1,
			char /*in*/cVal2);

	/**
	 * 
	 * @param iVal1 
	 */
	void operation1(int /*in*/iVal1);

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Package1

/************************************************************
 End of Class8 class header
 ************************************************************/

#endif
