/**
 * generated by Xtext
 */
package org.eclipse.papyrus.infra.gmfdiag.generator;

import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.IFileSystemAccess;
import org.eclipse.xtext.generator.IGenerator;

@SuppressWarnings("all")
public class CSSGenerator implements IGenerator {
	@Override
	public void doGenerate(final Resource resource, final IFileSystemAccess fsa) {
	}
}
