// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define CppCodegenTest_Package1_Class9_BODY

/************************************************************
 Class9 class body
 ************************************************************/

// include associated header file
#include "CppCodegenTest/Package1/Class9.h"

// Derived includes directives

namespace Package1 {

// static attributes (if any)

/**
 * 
 * @param  
 */
int Class9::volatileIntOperation() {

}

/**
 * Should not generate the 'register' keyword as it cannot be used in method signatures.
 * @param  
 */
int Class9::registerOperation() {

}

/**
 * 
 * @param  
 */
int Class9::externOperation() {

}

} // of namespace Package1

/************************************************************
 End of Class9 class body
 ************************************************************/